### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by giulianelealves** [IBM/marked-it#39]
I'm getting the following error when trying to run the **marked-it-cli** command (it uses the **--keyref-file** option only), and I'm not sure how to solve it.

```
Generating HTML files...

*WARNING: Invalid heading: Dependencies (level=2 depth=0) in connection_dependencie.html
*WARNING: Invalid heading: Dependencies (level=2 depth=0) in dependencies.html
*WARNING: Invalid heading: culture parameter options (level=3 depth=0) in culture.html
*WARNING: Invalid heading: Supported terminal emulators (level=3 depth=0) in supported.html
C:\Users\_<MY_USER>_\AppData\Roaming\npm\node_modules\marked-it-cli\node_modules\markdown-it-attrs\utils.js:271
  if (tokens[i].type === 'softbreak') {
                ^

TypeError: Cannot read properties of undefined (reading 'type')
    at Object.exports.getMatchingOpeningToken (C:\Users\<MY_USER>\AppData\Roaming\npm\node_modules\marked-it-cli\node_modules\markdown-it-attrs\utils.js:271:17)
    at Object.transform (C:\Users\<MY_USER>\AppData\Roaming\npm\node_modules\marked-it-cli\node_modules\markdown-it-attrs\patterns.js:170:34)
    at Array.curlyAttrs (C:\Users\<MY_USER>\AppData\Roaming\npm\node_modules\marked-it-cli\node_modules\markdown-it-attrs\index.js:33:19)
    at Core.process (C:\Users\<MY_USER>\AppData\Roaming\npm\node_modules\marked-it-cli\node_modules\markdown-it\lib\parser_core.js:51:13)
    at MarkdownIt.parse (C:\Users\<MY_USER>\AppData\Roaming\npm\node_modules\marked-it-cli\node_modules\markdown-it\lib\index.js:524:13)
    at MarkdownIt.render (C:\Users\<MY_USER>\AppData\Roaming\npm\node_modules\marked-it-cli\node_modules\markdown-it\lib\index.js:544:36)
    at Object.generate (C:\Users\<MY_USER>\AppData\Roaming\npm\node_modules\marked-it-cli\node_modules\marked-it-core\lib\htmlGenerator2.js:277:21)
    at Object.generate (C:\Users\<MY_USER>\AppData\Roaming\npm\node_modules\marked-it-cli\node_modules\marked-it-core\lib\marked-it.js:85:32)
    at generateHTML (C:\Users\<MY_USER>\AppData\Roaming\npm\node_modules\marked-it-cli\lib\mdProcessor.js:639:33)
    at generateHTML (C:\Users\<MY_USER>\AppData\Roaming\npm\node_modules\marked-it-cli\lib\mdProcessor.js:560:7)

Node.js v17.5.0
```

**Comment by grant-g** [comment]
Hi, the problem needs to be reproducible locally. Can you give either a pointer or an attachment of the source markdown file that causes this problem? If you're not sure which file is causing it then you can run marked-it-cli with switch `--verbose` to make it log each file as it's read and written.

**Comment by grant-g** [comment]
This can be reproduced in the original markdown-it-attrs dependency with the following content:
```
{: a} [b](c)
```

I've tried this case with the latest markdown-it and markdown-it-attrs releases and it no longer fails. So need to either move up to newer releases of these packages or determine if the fix for this case can be back-ported to our fork of markdown-it-attrs.
